# =========================
# BASIC CONFIG (SAFE MVP)
# =========================

bind 0.0.0.0
protected-mode yes
port 6379

# =========================
# MEMORY LIMIT (IMPORTANT)
# =========================
# évite que Redis explose la RAM
maxmemory 256mb

# stratégie quand plein
maxmemory-policy allkeys-lru

# =========================
# PERSISTENCE (optionnel MVP)
# =========================

save 900 1
save 300 10
save 60 10000

dbfilename dump.rdb
dir /data

# =========================
# LATENCY OPTIMIZATION
# =========================

tcp-keepalive 300

# =========================
# SECURITY (BASIC)
# =========================
# (optionnel si prod public)
# requirepass change_me_later